### ISSUE TITLE
Trying to run example

### ISSUE THREAD

**Issue by gannodg** [o19s/SemanticSearchInNumpy#1]
I am trying to follow along with your example and have run into an issue.  I'm running Python 3.3.2 and get the following error when trying to do this step: python extractDocs.py "<full_path_to_stack_exchange_dump>/posts.xml".  Specifically, I get this error: 

  File "extractDocs.py", line 35
    print resp.read() #TODO do someting smarter

Any idea what might be causing this?

**Comment by iamprakashom** [comment]
Try running with python 2.7. It works fine.

**Comment by Mnnu-Ann** [comment]
when I executed the statement **python SemanticAnalyzer.py Body** following error was returned 


COLLECTING TERMS
Traceback (most recent call last):
  File "SemanticAnalyzer.py", line 307, in <module>
    main(field,collection,solrUrl)
  File "SemanticAnalyzer.py", line 275, in main
    tdc = TermDocCollection(source=stvc,numTopics=150)
  File "SemanticAnalyzer.py", line 115, in __init__
    for termVector in source:
  File "SemanticAnalyzer.py", line 60, in next
    data = tv[3] #all of the terms and features in this vector
IndexError: list index out of range


what should I do ???

**Comment by anshumankaku** [comment]
is there any changes that needs to be done in this to work with python 3.7?
